### ISSUE TITLE
lab 2

### ISSUE THREAD

**Issue by lasbio** [PeryshkovaP/db-labs#3]
1. Если на сервере будет переназначена БД по умолчанию, то все скрипты будут выдавать ошибку.
2. Хорошим тоном считается запись всех sql команд заглавными буквами, а все остальное малыми.

**Comment by irinamatveeva** [comment]
Задание 5 - условие "не превышающий", то есть <= , а не <
Задание 7 - рекомендуется OR использовать IN(....)
Задание 9 - нужно выбрать не все букинги (аренду), а пользователей. Их не так много.
Задание 11 - как различить какой ряд в возвращаемом результате относится к member, а какой к facility?
Задание 12 - нужно найти дату последней регистрации члена клуба, а не брони объекта.
Задание 13 - то же самое.
Задание 14 - надо бы наверно подписать, какой самый дорогой и какой самый дешевый. И точно ли нужно использовать initialoutlay?

**Comment by PeryshkovaP** [comment]
Исправлено.

**Comment by lasbio** [comment]
Задание 9. У Вас сделана выборка "за сентябрь 2012 года", а в условии стоит "с сентября 2012 года"

**Comment by PeryshkovaP** [comment]
Поняла, исправила

**Comment by lasbio** [comment]
KЗачтено, но в задании 9 условие можно задать проще: joindate >= '2012-09-01'
