### ISSUE TITLE
Лаб 3

### ISSUE THREAD

**Issue by lasbio** [PeryshkovaP/db-labs#7]
1. Задание 2. Вы пытаетесь работать с базой данных как с "застывшей, неизменной сущностью".   Как Вы думаете продолжит ли Ваш скрипт работать корректно если  кто-то  зарегистрирует новый теннисный корт  (Tennis court 3)  или  заменит название  (исправит  предыдущую случайную ошибку в названии)  объекта с facid = 5  на теннисный корт (Tennis court 4).
2. задание 4. В вашей выборке отсутствуют члены, которые зарегистрировались без рекомендации.
3. задание 6 - не верно. Во-первых, у Вас в WHERE  условия ">30" применяются для всех. Например,  если резервирование стоит для гостя  35, а члена 25, то эта запись не будет отобрана даже если она сделана гостем.  Во-вторых, стоимость бронирования  == {стоимость единичной (на 30 минут) аренды объекта (guestcost или membercost)}  *  {количество аренд в день (bookings.slots) }.
4. Задание 7 - не верно.  В задании указано, что следует записать выборку без использования JOIN.

**Comment by PeryshkovaP** [comment]
Задание 2 исправлено.

**Comment by PeryshkovaP** [comment]
Задание 4 исправлено

**Comment by PeryshkovaP** [comment]
Задание 6 исправлено.

**Comment by PeryshkovaP** [comment]
Задание 7 исправлено.

**Comment by lasbio** [comment]
Задание 6 - работает, но не оптимально.  HAVING предназначено для фильтрации групповых записей, а WHERE для фильтрации единичных записей.   Другими словами,  для вашего скрипта,  будут выполнены следующие действия: 
(а) отобраны (т.е. извлечены из базы в память) все записи из таблицы на указанную дату (включая те, которые не удовлетворяют условию < 30);
(б)  над всеми отобранными записями будут свершены все действия (в данном конкретном случае - CASE, хотя в дрпугих случаях это могут быть более ресурсозатратные функции);
(в) поскольку групповых функций (SUM, COUNT...) и группировки  (GROUP BY)  нет, а HAVING есть, то  каждая отобранная запись будут интерпретироваться как псевдогруппа;  все "псевдогруппы" подвергнуться фильтрации в соответствии с условием заданном в HAVING, т.е. записи не удовлетворяющие условию "< 30"  будут отброшены (т.е. останутся в памяти в виде "мусора", который потом уберет оптимизатор сервера MySQL);
(г) отфильтрованные "псевдогруппы" будут  возвращены пользователю.
Если же все условия на единичные записи задать в WHERE, то сразу будут отобраны только те записи, которые нужны и над ними будут совершены действия (CASE). 
Как численный пример: Предположим,  в базе данных 10 млн записей на указанную дату и среди них только 3, которые удовлетворяют условиям на цену. В скрипте с HAVING будет 10 млн (отбор данных по дате) + 3 (отбор по HAVING) действий, в при использовании WHERE только 3 действия (т.к. если правильно построены индексы, то по индексу будут изначально отбираться только 3 записи). Дополнительно надо учитывать, что изначально данные находятся в БД (т.е. в файлах), поэтому отбор в память == чтение с диска, а работа с диском она из самых затратных операций. 
Попробуйте сконструировать скрипт без HAVING. 

Задание 7 - не верно. Например, если мы посмотрим всех зарегистрированных Смитов (select * from members m1 WHERE m1.surname = 'Smith';), то окажется, что в  базе их зарегистрировано 5.  А если добавить к вашему скрипту условие m1.surname = 'Smith', то он вернет только одного, т.е. 4 будет потеряно.

**Comment by PeryshkovaP** [comment]
Задание 6 исправлено.

**Comment by PeryshkovaP** [comment]
В 7 задание получилось вывести Smith, но есть проблема с выводом второго столбца. Код обновила, но будет выводится только столбец с ФИО участника без того, кто его порекомендовал

**Comment by lasbio** [comment]
6 - идея правильная, но возникает вопрос зачем еще раз использовать CASE. Разве нельзя записать условия фильтрации  без его использования?

7 - по условиям задачи надо выводить и члена клуба и его рекомендателя.  Кроме того, использованные условия явно неоптимальны.  Более того, если в Вашем скрипте убрать WHERE полностью, то выведется та же выборка. Думайте. Даю подсказку - Derived table.

**Comment by PeryshkovaP** [comment]
Задание 6 исправлено.

**Comment by lasbio** [comment]
7 - пока не выполнено

**Comment by PeryshkovaP** [comment]
Задание 7 исправлено
